wip

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -32,7 +32,7 @@ jobs:
       run: |
         mkdir -p /home/runner/.state
         CUR_BRANCH=${GITHUB_REF//\//_}
-        echo "aaaaa $CUR_BRANCH"
+        STATE_FILE="/home/runner/.state/$CUR_BRANCH-failed"
 
         cd gha-test-lib
         #git remote set-url origin ${{ github.repositoryUrl }} - this is git:// and GHA doesn't seem to like it
@@ -41,13 +41,18 @@ jobs:
         git checkout gha-test
         cd ..
 
-        cargo build --verbose || {
+        cargo build --verbose && {
+          if [ -f "$STATE_FILE" ]; then
+            echo "We previously failed building, but now we succeeded."
+            rm $STATE_FILE
+            echo "UPREV_FIXED=1" >> "$GITHUB_ENV"
+          fi
+         } || {
           # We failed building, so first keep track of that in the env so that the next steps
           # can access this information.
           echo "UPREV_FAILED=1" >> "$GITHUB_ENV"
 
           # If this a new failure?
-          STATE_FILE="/home/runner/.state/$CUR_BRANCH-failed"
           if [ -f "$STATE_FILE" ]; then
             echo "Not the first time this branch failed, so we won't be posting an update on that."
             echo "NEW_FAILURE=0" >> "$GITHUB_ENV"
@@ -72,12 +77,22 @@ jobs:
 
 
 
-    - name: Comment on PR
+    - name: Comment on PR (failure)
       uses: mshick/add-pr-comment@v1
       if: env.UPREV_FAILED == '1' && env.BASE_FAILED == '0' && env.NEW_FAILURE == '1'
       with:
         message: |
           Heads up, I tried building XXX using this branch and it failed.
+        repo-token: ${{ secrets.GITHUB_TOKEN }}
+        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
+        allow-repeats: true # This is the default
+
+    - name: Comment on PR (success)
+      uses: mshick/add-pr-comment@v1
+      if: env.UPREV_FIXED == '1'
+      with:
+        message: |
+          ✅ Good job, XXX was built successfully.
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
         allow-repeats: true # This is the default
